# Generated by Django 3.2.25 on 2026-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50)),
                ('job_date', models.CharField(max_length=20)),
                ('copies', models.CharField(max_length=50)),
                ('ink', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('binding_type', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=150)),
                ('item_size', models.CharField(max_length=100)),
                ('page', models.DecimalField(decimal_places=2, max_digits=12)),
                ('page_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('page_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plates', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plates_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plates_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_name', models.CharField(max_length=150)),
                ('other_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sheets', models.CharField(max_length=100)),
                ('paper_size', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('gsm', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=150)),
                ('paper_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lamination', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_paper', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_by', models.CharField(max_length=100)),
                ('paid_date', models.CharField(max_length=20)),
                ('through', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
