# Generated by Django 3.2.25 on 2026-08-11 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BindingThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Binding through options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BindingVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Binding outsource vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Paper through options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Paper vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintingJobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.PositiveIntegerField(editable=False, unique=True)),
                ('job_date', models.DateField(default=django.utils.timezone.localdate)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('page', models.PositiveIntegerField(default=0)),
                ('copies', models.PositiveIntegerField(default=0)),
                ('ink', models.CharField(blank=True, max_length=100)),
                ('ss_fb', models.CharField(blank=True, max_length=50)),
                ('binder', models.CharField(blank=True, max_length=100)),
                ('printing_plates_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_plates_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_plates_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_ptg_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_ptg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_ptg_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_lam_uv', models.CharField(blank=True, max_length=150)),
                ('printing_lam_uv_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_bdg', models.CharField(blank=True, max_length=150)),
                ('printing_bdg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_other_gst', models.CharField(blank=True, max_length=150)),
                ('printing_other_gst_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_paper_details', models.CharField(blank=True, max_length=150)),
                ('printing_paper_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_paid_rs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('printing_paid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('printing_reference', models.CharField(blank=True, max_length=150)),
                ('paper_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paper_size', models.CharField(blank=True, max_length=100)),
                ('paper_quality', models.CharField(blank=True, max_length=100)),
                ('paper_gsm', models.CharField(blank=True, max_length=50)),
                ('paper_total_rs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paper_discount_2', models.CharField(blank=True, max_length=150)),
                ('paper_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paper_paid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('paper_reference', models.CharField(blank=True, max_length=150)),
                ('paper_total_paid_display', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paper_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('binding_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('binding_rate_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('binding_total_rs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('binding_discount', models.CharField(blank=True, max_length=150)),
                ('binding_paid_rs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('binding_paid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('binding_reference', models.CharField(blank=True, max_length=150)),
                ('binding_total_paid_display', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('binding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('summary_prev_bal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('summary_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('binding_total_of_this_job', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-job_no'],
            },
        ),
        migrations.CreateModel(
            name='PrintingThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Printing through options',
                'ordering': ['name'],
            },
        ),
    ]
