# Generated by Django 3.2.25 on 2026-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.EmailField(blank=True, max_length=254)),
                ('mail_to', models.EmailField(blank=True, max_length=254)),
                ('mail_cc', models.EmailField(blank=True, max_length=254)),
                ('starting_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System value',
                'verbose_name_plural': 'System values',
            },
        ),
    ]
