# Generated by Django 3.2.25 on 2026-08-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0002_systemvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Job styles',
                'ordering': ['name'],
            },
        ),
    ]
