# Generated by Django 3.2.25 on 2026-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0003_jobstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingjobsheet',
            name='binding_thru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='binding_vendor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='job_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='paper_thru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='paper_vendor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='printing_thru',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
