# Generated by Django 3.2.25 on 2026-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0004_auto_20260811_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingjobsheet',
            name='binding_thru_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='binding_vendor_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='job_style_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='paper_thru_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='paper_vendor_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingjobsheet',
            name='printing_thru_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
