# Generated by Django 3.2.25 on 2026-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0005_auto_20260811_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjobsheet',
            name='copies',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='page',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
