# Generated by Django 3.2.25 on 2026-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0006_auto_20260811_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjobsheet',
            name='printing_lam_uv',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='printing_other_gst',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='printing_paper_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='printing_reference',
            field=models.TextField(blank=True),
        ),
    ]
