# Generated by Django 3.2.25 on 2026-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0007_auto_20260811_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjobsheet',
            name='paper_gsm',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='paper_qty',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='paper_quality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='paper_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='paper_size',
            field=models.TextField(blank=True),
        ),
    ]
