# Generated by Django 3.2.25 on 2026-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_entry', '0008_auto_20260811_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjobsheet',
            name='binding_qty',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='binding_rate_rate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printingjobsheet',
            name='binding_reference',
            field=models.TextField(blank=True),
        ),
    ]
